/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginForm.java
 *
 * Created on Oct 15, 2011, 1:58:27 AM
 */
package yahoomessengertts;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.KeyEvent;
import org.openymsg.network.Session;
import org.openymsg.network.event.SessionAdapter;
import org.openymsg.network.event.SessionEvent;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahid Chohan
 */
public class LoginForm extends javax.swing.JFrame {
    String sn = "";
    String pw = "";
    /** Creates new form LoginForm */
    public LoginForm() {
        initComponents();
        Container cp = getContentPane();
        cp.setBackground(new Color(119,36,111));
        usernameLabel.setForeground(new Color(255,255,255));
        passwordLabel.setForeground(new Color(255,255,255));
        usernameField.setText("");
        passwordField.setText(""); 
        icon.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setText("Yahoo! ID:");
        usernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        usernameField.setText("jTextField1");

        passwordLabel.setText("Password:");
        passwordLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shahid Chohan\\Dropbox\\HackU\\Yahoo!_Messenger_logo.png")); // NOI18N
        icon.setText("jLabel1");

        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        signInButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signInButtonKeyPressed(evt);
            }
        });

        passwordField.setText("jPasswordField1");
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(signInButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField)
                            .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(usernameLabel)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(passwordLabel)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon)
                .addGap(22, 22, 22)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(signInButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
                pw = passwordField.getText();
                sn = usernameField.getText();
                final Session sender = new Session();
                final ReceiveMessageAdaptor listener = new ReceiveMessageAdaptor();
                try
                {
                    sender.login(sn, pw);
                    MessageForm mf = new MessageForm();
                    mf.main(sn,pw);
                    sender.logout();
                    this.setVisible(false);
                    //JOptionPane.showMessageDialog (null, "SUCCESS" , "Successful Login", JOptionPane.INFORMATION_MESSAGE);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog (null, "Wrong Username/Password Combination" , "Incorrect Password", JOptionPane.INFORMATION_MESSAGE);
                }
    
    }//GEN-LAST:event_signInButtonActionPerformed

    private void signInButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signInButtonKeyPressed
        
        
        
    }//GEN-LAST:event_signInButtonKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            pw = passwordField.getText();
                sn = usernameField.getText();
                final Session sender = new Session();
                final ReceiveMessageAdaptor listener = new ReceiveMessageAdaptor();
                try
                {
                    sender.login(sn, pw);
                    MessageForm mf = new MessageForm();
                    mf.main(sn,pw);
                    sender.logout();
                    this.setVisible(false);
                    //JOptionPane.showMessageDialog (null, "SUCCESS" , "Successful Login", JOptionPane.INFORMATION_MESSAGE);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog (null, "Wrong Username/Password Combination" , "Incorrect Password", JOptionPane.INFORMATION_MESSAGE);
                }}
    }//GEN-LAST:event_passwordFieldKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main() {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }
    private static class ReceiveMessageAdaptor extends SessionAdapter {
       
        private SessionEvent sessionEvent = null;

        public ReceiveMessageAdaptor() {
            // doesn't do much, but prevens synthetic accessor warnings.
        }

        /*
         * (non-Javadoc)
         * 
         * @see org.openymsg.network.event.SessionAdapter#messageReceived(org.openymsg.network.event.SessionEvent)
         */
        @Override
        public void messageReceived(SessionEvent event) {
            this.sessionEvent = event;
        }

        /**
         * Waits for a particular amount of time for the next event to arrive, and then returns that event. If within
         * the timeout no event has been received, this method returns null.
         * 
         * @param timeout_in_millis
         *            The time (in milliseconds) to wait for the next event.
         * @return 'null' or the first event that arrived within the timeout value.
         */
        public SessionEvent waitForNextEvent(long timeout_in_millis) {
            if (timeout_in_millis < 0) {
                throw new IllegalArgumentException("Cannot use negative timeout values.");
            }

            if (sessionEvent != null) {
                throw new IllegalStateException("There's already an event queued, before this method was called.");
            }

            final long STEP_IN_MILLIS = 100;
            SessionEvent result = null;
            for (int i = 0; i < timeout_in_millis; i += STEP_IN_MILLIS) {
                if (sessionEvent != null) {
                    result = sessionEvent;
                    break;
                }

                try {
                    Thread.sleep(STEP_IN_MILLIS);
                }
                catch (InterruptedException e) {
                    // ignore
                }
            }

            sessionEvent = null;
            return result;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signInButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}

